apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: flask-app
  namespace: flux-system
spec:
  image: 839507877817.dkr.ecr.us-west-2.amazonaws.com/legacy-ecommerce-app
  interval: 1m0s
