apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-gitops
  namespace: flask-demo
  labels:
    app: flask-gitops
    managed-by: fluxcd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-gitops
  template:
    metadata:
      labels:
        app: flask-gitops
    spec:
      containers:
      - name: flask
        image: 813274479812.dkr.ecr.us-west-2.amazonaws.com/legacy-flask-app:v1.2
        ports:
        - containerPort: 8000
        command: ["gunicorn"]
        args: ["--bind", "0.0.0.0:8000", "--workers", "4", "app:app"]
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: FLASK_ENV
          value: "production"
        - name: MANAGED_BY
          value: "fluxcd"
