apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: testingworkshop
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: testingworkshop
  filterTags:
    pattern: '.*'
  policy:
    numerical:
      order: desc
