apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: testingworkshop
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flask-gitops
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcd@users.noreply.github.com
        name: fluxcd
      messageTemplate: 'Update image to {{range .Updated.Images}}{{.}}{{end}}'
    push:
      branch: main
  update:
    path: ./gitops/flask-app
    strategy: Setters
